import { Inter } from "next/font/google";
import "./globals.css";
import "../../public/sass/global.scss";
import "../../public/sass/helper/base.scss";
import "../../public/sass/helper/helper.scss";
import "../../public/sass/helper/reset.scss";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import ClientThemeProvider from "./components/ClientThemeProvider";

const inter = Inter({ subsets: ["latin-ext"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} id="pb_scroll">
        <ClientThemeProvider>
          <Navbar /> 
          {children}
          <Footer/>
        </ClientThemeProvider>
      </body>
    </html>
  );
}
