import { Cookie, Inter } from "next/font/google";
import "./globals.css";
import "../../public/sass/global.scss";
import "../../public/sass/helper/base.scss";
import "../../public/sass/helper/helper.scss";
import "../../public/sass/helper/reset.scss";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import ClientThemeProvider from "./components/ClientThemeProvider";
import Contact from "./components/contactUs";
import Login from "./(screens)/auth/login/page";
import SignIn from "./(screens)/auth/signup/page";
import Forgotpass from "./(screens)/auth/forgotpassword/page";
import Reset from "./(screens)/auth/reset/page";
import Homepage from "./components/homepage";
import About from "./components/aboutUs";
import Dummy from "./components/dummy";
import Blog from "./components/blogs";
import Fullblog from "./components/fullblog";
import Term from "./components/terms";
import Privacy from "./components/privacy";
import Cookie_policy from "./components/cookie";

const inter = Inter({ subsets: ["latin-ext"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) { 
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientThemeProvider>
        <Navbar/>
       {<Cookie_policy/>}
        <Footer/>
        </ClientThemeProvider>
      </body>
    </html>
  );
}
